name: load_dataset
on: [workflow_dispatch]
jobs:
  load_dataset:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: download source from kaggle
        env:
          KAGGLE_TOKEN: ${{secrets.KAGGLE_TOKEN}}
        run: |
          echo $KAGGLE_TOKEN > $HOME/.kaggle/kaggle.json
          kaggle datasets download -d rounakbanik/the-movies-dataset
          unzip the-movies-dataset.zip -d resources/
      - name: load
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 src/load_dataset.py

  preprocess:
    runs-on: self-hosted
    needs: load_dataset
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Preprocess dataset
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD:  ${{secrets.DB_PASSWORD}}
        run: python3 src/preprocess.py
