name: load_dataset
on: [workflow_dispatch]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: download source from kaggle
        run: |
          sudo apt-get install unzip
          pip install kaggle
          mkdir $HOME/.kaggle
          echo $KAGGLE_TOKEN > $HOME/.kaggle/kaggle.json
          kaggle datasets download -d rounakbanik/the-movies-dataset
          mkdir -p assets/source-data/
          unzip the-movies-dataset.zip -d assets/source-data/

  preprocess:
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Preprocess dataset
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD:  ${{secrets.DB_PASSWORD}}
        run: python3 src/preprocess_dataset.py
