name: main
on:
  workflow_dispatch:
    inputs:
      is_train:
        description: Are models already trained
        required: true
        default: 'true'
jobs:
  train:
    if: ${{ github.event.inputs.is_train == 'true' }}
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: fit models
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 src/fit.py

      - name: commit version change
        uses: EndBug/add-and-commit@v9.1.1
        with:
            default_author: github_actions
            message: 'version change'

  extra_train:
    if: ${{ github.event.inputs.is_train == 'false' }}
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: extra train
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 src/refit.py

  estimate:
    runs-on: self-hosted
    needs: [train, extra_train]
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: estimate
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: | 
          cat resources/model_version.txt
          python3 src/estimate.py

  selection:
    runs-on: self-hosted
    needs: estimate
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: select best model
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python3 src/selection.py

  deploy:
    runs-on: self-hosted
    needs: selection
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: deployment
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: curl "http://localhost:5000/update"
